security:
    
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
            
    providers:
        liga_typerow_users:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        liga_typerow_security:
            switch_user: true
            pattern:    ^/
            anonymous: ~
            form_login:
                check_path: _check_path
                login_path: liga_typerow_login
                default_target_path: liga_typerow_index
            logout:
                path:   _logout
                target: liga_typerow_index
                
    access_control:
#        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
         - { path: ^/admin-panel, roles: ROLE_SUPER_ADMIN }
         - { path: ^/account, roles: ROLE_USER }
