parameters:
    activity_listener.class: AppBundle\EventListener\ActivityListener

services:
    activity_listener:
        class: %activity_listener.class%
        arguments: [@security.context, @doctrine.orm.entity_manager]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }
            
    result_listener:
        class: AppBundle\EventListener\ResultListener 
        tags:
            - { name: doctrine.event_listener, event: postUpdate }