parameters:
    activity_listener.class: AppBundle\EventListener\ActivityListener

services:
    activity_listener:
        class: %activity_listener.class%
        arguments: [@security.context, @doctrine.orm.entity_manager]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }
            
    result_listener:
        class: AppBundle\EventListener\ResultListener 
        tags:
            - { name: doctrine.event_listener, event: postUpdate }
            
    user_manager:
        class: AppBundle\Manager\UserManager
        arguments: [@doctrine, @security.encoder_factory]
        
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: true
        arguments: 
            doctrine : '@doctrine'
        tags:
            - { name: twig.extension }